# Configure navigation menu url, icon and enable
# 配置导航菜单的url, 图标及是否启用
menu:
  index:
    enable: true
    url: /
    icon: fas fa-home
    material_icon: home
  categories:
    enable: true
    url: /categories
    icon: fas fa-bookmark
    material_icon: chrome_reader_mode
  archives:
    enable: true
    url: /archives
    icon: fas fa-archive
    material_icon: inbox
  tags:
    enable: true
    url: /tags
    icon: fas fa-tags
    material_icon: label
  about:
    enable: true
    url: /about
    icon: fas fa-portrait
    material_icon: person
  comments:
    enable: true
    url: /comments
    icon: fas fa-comments
    material_icon: comment
  frients:
    enable: true
    url: /frients
    icon: fas fa-address-book
    material_icon: link
  resume:
    enable: true
    url: /resume
    icon: fas fa-briefcase
    material_icon: work
  timeline:
    enable: true
    url: /timeline
    icon: fas fa-calendar-alt
    material_icon: timeline
  medias:
    enable: true
    icon: fas fa-list
    material_icon: perm_media
    children:
      galleries:
        enable: true
        url: /galleries
        icon: fas fa-image
        material_icon: photo_library
      musics:
        enable: true
        url: /musics
        icon: fas fa-music
        material_icon: library_music
      videos:
        enable: true
        url: /moveis
        icon: fas fa-film
        material_icon: video_library
      books:
        enable: true
        url: /books
        icon: fas fa-book
        material_icon: library_books

# config favicon and logo
# 配置favicon和logo
favicon: /img/favicon.png
logo: /img/logo.png
banner:

# Sidebar
sidebar: right

# Posts TOC
# 文章目录
toc:
  enable: true
  show_toggle_btn: true
  position: right   # left or right

# SNS
# 社交网络服务
sns:
  github: https://github.com/xiongxianzhu
  email: 929679459@qq.com
  facebook: # https://www.facebook.com/xxx
  twitter: # https://twitter.com/xxx
  googleplus:
  instagram:
  tumblr:
  linkedin:
  telegram:
  qq: 929679459
  weibo: # https://weibo.com/xxx
  zhihu: # https://www.zhihu.com/xxx
  juejin: https://juejin.cn/user/1714893867985389
  bilibili: https://space.bilibili.com/200731874
  v2ex:
  segmentfault:
  rss: true

# Enable the back to top button
# 是否启用快速回到顶部按钮
top: true

# copyright
# 版权
copyright:
  since: # 2021

# ================
# Comment System
# ================
# 评论系统
# disqus comment
disqus:
  enable: true
  shortname: blog-zhuxiongxian

# gitalk comment
gitalk:
  enable: false
  owner:
  repo:
  oauth:
    client_id:
    client_secret:
  admin:

# gitment comment
gitment:
  enable: false
  owner:
  repo:
  oauth:
    client_id:
    client_secret:

# livere comment
# 来必力评论系统
livere:
  enable: false
  uid:

# valine comment system. https://valine.js.org
valine:
  enable: false # if you want use valine,please set this value is true
  app_id:  # leancloud application app id
  app_key:  # leancloud application app key
  notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
  verify: false # valine verify code (true/false)
  page_size: 10 # comment list page size
  avatar: mm # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link # valine comment header info

# changyan comment
# 畅言评论系统， 需要备案
changyan:
  enable: false
  app_id:
  conf:

# DaoVoice online contact
daovoice:
  enable: false
  app_id:

# frontend libraries
# 前端插件库
# 默认使用本主题下的前端库文件地址， 可替换成对应的绝对路径的CDN地址
# 免费的CDN推荐： jsDelivr， BootCDN, cloudflare
libs:
  css:
    fontawesome: /libs/fontawesome/css/all.min.css
    materialize: /libs/materialize/materialize.min.css
    animate: /libs/animate.css/animate.min.css
    gitalk:
    prism: /libs/prism/prism-tomorrow-night.css
    material_icons: https://fonts.googleapis.com/icon?family=Material+Icons
    aos: /libs/aos/aos.css
    xxcoding: /css/xxcoding.css
    mycss: 
  js:
    jquery: /libs/jquery/jquery.min.js
    materialize: /libs/materialize/materialize.min.js
    lazyload: /libs/lazyload/lazyload.min.js
    aos: /libs/aos/aos.js
    gitalk:
    busuanzi:
    xxcoding: /js/xxcoding.js
    myjs: 
  fontcss:
    - https://fonts.googleapis.com/css?family=Roboto:300,400,500
    - https://fonts.googleapis.com/css?family=Marck+Script


google_analytics:
busuanzi_analytics:

icp:
  enable: true
  url: https://beian.miit.gov.cn/
  text: 粤ICP备17065679号-1

random_thumbnail:
  - /img/random/material-1.jpg
  - /img/random/material-2.jpg
  - /img/random/material-3.jpg
  - /img/random/material-4.jpg
  - /img/random/material-5.jpg
  - /img/random/material-6.jpg
  - /img/random/material-7.jpg
  - /img/random/material-8.jpg
  - /img/random/material-9.jpg
  - /img/random/material-10.jpg
  - /img/random/material-11.jpg
  - /img/random/material-12.jpg
  - /img/random/material-13.jpg
  - /img/random/material-14.jpg
  - /img/random/material-15.jpg
  - /img/random/material-16.jpg
  - /img/random/material-17.jpg
  - /img/random/material-18.jpg
  - /img/random/material-19.jpg
  - /img/random/material-20.jpg
  - /img/random/material-21.jpg
  - /img/random/material-22.jpg
  - /img/random/material-23.jpg
  - /img/random/material-24.jpg
  - /img/random/material-25.jpg
  - /img/random/material-26.jpg
  - /img/random/material-27.jpg
  - /img/random/material-28.jpg
  - /img/random/material-29.jpg
  - /img/random/material-30.jpg
  - /img/random/material-31.jpg
  - /img/random/material-32.jpg
  - /img/random/material-33.jpg
  - /img/random/material-34.jpg
  - /img/random/material-35.jpg
  - /img/random/material-36.jpg
  - /img/random/material-37.jpg
  - /img/random/material-38.jpg

carousel:
  show_indicators: true
  auto_loop: true
  interval_time: 5000
  duration: 200
  indicators: true
